### ISSUE TITLE
aws-smithy-runtime-api 1.6.1 causes S3 HEAD requests to fail

### ISSUE THREAD

**Issue by bryanburgers** [smithy-lang/smithy-rs#3656]
When using `aws-smithy-runtime-api` version `1.6.1` all S3 head requests fail with an error like:

> Invalid Content-Length: Expected 13793 bytes but 0 bytes were received

When using `aws-smithy-runtime-api` version `1.6.0` S3 head requests succeed.

```toml
[package]
name = "z-2024-05-21-s3-head-object"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
aws-config = "1.4.0"
aws-sdk-s3 = "1.29.0"
aws-smithy-runtime-api = "=1.6.0"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
```

```rust
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let config = aws_config::load_defaults(aws_config::BehaviorVersion::latest()).await;
    let client = aws_sdk_s3::Client::new(&config);

    let result = client
        .head_object()
        .bucket("<redacted>")
        .key("<redacted>")
        .send()
        .await?;
    println!("{result:#?}");

    Ok(())
}
```
